package com.huhuo.mobiletest.model;

import java.util.Date;

public class HttpPage {
	public int ID ;
	public String APP_ServiceRequest;
	public float APP_MAX ;
	public float APP_MIN;
	public float APP_AVERAGE ;
	public String APP_URL;
	public float APP_DATA_SIZE ;
	public float APP_DOWNLOAD_TIME;
	public int APP_SENT_NUMBER;
	public int APP_SUCC_RECEIVED_NUMBER;
	public int APP_SHAKE_NUMBER ;
	public Date APP_CON_STIME ;
	public Date APP_CON_ETIME ;
	public String APP_CON_TYPE ;
	public Date APP_LOGIN_STIME ;
	public Date APP_LOGIN_ETIME ;
	public String APP_LOGIN_TYPE ;
	public Date APP_REQ_TIME ;
	public Date APP_RES_TIME ;
	public String APP_RES_TYPE ;
	public float APP_USER_FEELING_TIME ;
	public int APP_PROGRAM_TIME ;
	public float APP_PLAY_TIME ;
	public float APP_OPEN_TIME ;
	public float APP_CUSHION_TIME ;
	public float APP_CUSHION_TOTAL_TIME ;
	public float APP_CUSHION_NUMBER ;
	public String APP_FILE_BIT_RATE ;
	public String APP_ENCODING_INFORMATION ;
	public int APP_TTL_MIN ;
	public int APP_TTL_MAX ;
	public String APP_SERVICE_NAME ;
	public String APP_SERVICE_IP ;
	public String APP_GROUP_ID ;
	public String APP_GROUP_NAME ;
	public float APP_LON ;
	public float APP_LAT ;
	public String APP_GPS_COORDINATE ;
	public String APP_LOCATION ;
	public String APP_SUBGROUP_ID ;
	public String APP_SUBGROUP_NAME ;
	public String APP_COUNTY_TOWN_NAME ;
	public String APP_STREET_NAME ;
	public String APP_STREET_NUMBERL ;
	public String APP_VERSION_CODE ;
	public String APP_TEST_SCENARIO ;
	public String APP_TEST_LOCATION ;
	public int APP_VERSION ;
	public String APP_SOFT_VERSION ;
	public String APP_IMEI ;
	public String APP_IMSI ;
	public String APP_MSISDN ;
	public String APP_MANUFACTURE ;
	public String APP_TYPECODE ;
	public String APP_OS ;
	public String APP_BASEBAND ;
	public String APP_KERNEL ;
	public String APP_FAC_VER ;
	public String APP_IS_PUBLIC_LOG ;
	public Date APP_LOGTIME ;
	public String APP_NET_TYPE ;
	public String APP_NET_NAME ;
	public String APP_MCC ;
	public String APP_MNC ;
	public String APP_LAC ;
	public String APP_CI ;
	public float APP_RXLEVEL ;
	public String APP_TAC ;
	public String APP_ECI ;
	public float APP_RSRP ;
	public float APP_SCELL_PCI ;
	public float APP_CRS_SINR ;
	public float APP_RSRQ ;
	public float APP_QUALITY_STATE ;
	public String APP_QUALITY_CAUSE ;
	public int APP_PROBLEM ;
}
